@startuml
	class "main.sh" as main {
		+ main()
	}
	class "log_manager.sh" as log {
		+ get_logdir()
	}
	class "term_controller.sh" as term {
		+ input_numOfTerm()
	} 
	class "digit_controller.sh" as digit {
		+ input_digit()
		+ input_all_digit()
	}
	class "arith.sh" as arith {
		+ choose_arith()
		- add()
		- sub()
		- mul()
		- div()
	}

main ..> log: check and get log_dir.
arith ..> term: get nuber of term.
arith ..> digit: get inputted digit and place digit in each term.
main ..> arith: get calculate result.
term ..> log: import log path and save log.
digit ..> log: import log path and save log. 
@enduml
