@startuml
start
: run main.sh;
: get log path log_manager.sh from .env;
: load log path for each command;
note right
	test: "sudo ./main.sh"
	prod: "sudo ENV=prod ./main.sh"
end note

if (exit .env file?) then (yes)
	: export log path;
else (no)
	: show error message;
	: exit scripts(status1);
	kill
endif

if ("ENV=prod") then (yes)
	: log_dir = prod_log;
else (no)
	: log_dir = test_log;
endif

if (exist already a log directory?) then (yes)
	: pass;
else (no)
	: create a log directory;
endif
: load input_term() from digit_controller.sh;


repeat
: input number of terms; 
note right
number of term can be bet wenn 1 and 3
end note

switch("$input_term" is 1, 2, 3, 0 or other)
case(1)
	: add one term;
case(2)
	: add two terms;
case(3)
	: add three terms;
case(0)
	: exit scripts(status1);
	detach
case(other)
	: invalid input \n (ask again);
endswitch
backward: loop back to input_term; 
repeat while(input_term is other) is (yes) not (1, 2, 3);

: input digits for each term;

: load choic_arith() from arith.ah;
repeat
: choice a aritmetic via input number;
note right
1: add, 2: sub, 3:mul, 0: end
end note

switch ("$choice_arith" is  1, 2, 3, 4, 0 or other)
case (1)
	: add();
case (2)
	: sub();
case (3)
	: mul();
case (4)
	: div();
case (0)
	: exit scripts(status1);
	detach
case (other)
	: invalid input \n(ask again);
endswitch
backward: loop back to input_digit;
repeat while(choice_arith is other) is (yes) not (1, 2, 3, 4);

: execute input_term() from digit_controller.sh;
: load calc() from arith.sh;
: calculate;
: show the calulate result;
: save log;
stop
@enduml

